import {BUILD_ID,PROFILES,STUDY,ARMOR} from './hybrid-experiments.mjs?v=20261007-t035-1';
export const STORAGE_KEY='tanchiki-runs-v1';
let sequence=0;
export function createRun(match,meta={}){const p=PROFILES[match.experiment||'legacy'];return {schemaVersion:1,runId:`${Date.now()}-${++sequence}`,startedAt:new Date().toISOString(),rulesetId:match.experiment==='legacy'?`R0-${match.version}`:p.rulesetId,parentId:p.parentId,buildId:BUILD_ID,mapId:match.map,seed:match.cfg.seed,config:JSON.parse(JSON.stringify({...match.cfg,...(match.experiment!=='legacy'?{study:STUDY,...(match.experiment==='armor'?{armor:ARMOR}:{})}:{})})),bot:match.bot,inputType:meta.inputType||'keyboard',screen:meta.screen||null,origin:meta.origin||'manual',selectedReplay:null,timeSim:0,winner:null,completed:false,finishReason:null,events:[],eventsTruncated:false,summary:{shots:[0,0],hits:[0,0],baseDamage:[{tank:0,minion:0},{tank:0,minion:0}],firstBaseDamage:null,orders:[0,0],routes:[],shieldAbsorbed:[0,0],shieldRecharges:[0,0]},feedback:null};}
export function recordEvent(run,event,time){if(!run||run.finishReason)return;const e={...event,time};if(run.events.length<10000)run.events.push(e);else run.eventsTruncated=true;const s=run.summary;if(e.type==='shield_absorb')s.shieldAbsorbed[e.team]+=e.absorbedDamage;if(e.type==='shield_recharge')s.shieldRecharges[e.team]++;if(e.type==='fire')s.shots[e.team??Number(e.id[0])]++;if(e.type==='hit'&&e.attacker)s.hits[e.attacker.team]++;if(e.type==='order')s.orders[e.team]++;if(e.type==='line')s.routes.push({time,team:e.team,id:e.id,lane:e.lane});if(e.type==='baseDamage'){s.baseDamage[e.attacker.team][e.attacker.kind]+=e.appliedDamage;if(s.firstBaseDamage===null)s.firstBaseDamage=time;}}
export function recordStep(run,match){if(!run||run.finishReason)return;run.timeSim=match.time;for(const e of match.events)recordEvent(run,e,match.time);}
export function finishRun(run,match,reason){if(!run||run.finishReason)return run;run.timeSim=match.time;run.finishReason=reason;run.completed=['base_destroyed','draw'].includes(reason);run.winner=run.completed?match.winner:null;
 if(run.events.length<10000)run.events.push({type:'finish',reason,time:match.time});else run.eventsTruncated=true;return run;}
export function serializeRun(run){return JSON.stringify(run,null,2);}
export function createStore(storage){let runs=[],error=null;try{runs=JSON.parse(storage.getItem(STORAGE_KEY)||'[]').slice(-20);}catch(e){error='Хранилище недоступно: результаты доступны в памяти и для экспорта.';}
 function save(){try{storage.setItem(STORAGE_KEY,JSON.stringify(runs));}catch(e){error='Хранилище недоступно: результаты доступны в памяти и для экспорта.';}}
 return {get runs(){return runs;},get error(){return error;},put(run){const i=runs.findIndex(r=>r.runId===run.runId);if(i<0)runs.push(run);else runs[i]=run;runs=runs.slice(-20);save();},clear(){runs=[];save();},export(){return JSON.stringify({schemaVersion:1,runs},null,2);}};}
